# Hospital Patient Data Analysis

In [1]:
# Importing necessary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Loading reading Data

bill = pd.read_csv(r"D:\Excelr\Data Sceince\Python\Assignments_docs\Assignmemts_4\Billing_Data.csv")
pinfo = pd.read_csv(r"D:\Excelr\Data Sceince\Python\Assignments_docs\Assignmemts_4\Patient_Data (1).csv")

In [3]:
bill

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [4]:
bill.isnull().sum()

PatientID           0
InsuranceCovered    0
FinalAmount         0
dtype: int64

In [5]:
pinfo.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

In [6]:
pinfo

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

## TASKS

In [7]:
# 1. summary with info

print("Patient Information")
print()
print(pinfo.info())

Patient Information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes
None

In [8]:
# 2. Selecting relevant columns for billing

billing_cols = ['PatientID', 'Department', 'Doctor', 'BillAmount']
pinfo1 = pinfo[billing_cols]
pinfo1

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [9]:
# 3. Droping administrative columns

pinfo = pinfo.drop(columns = ['ReceptionistID', 'CheckInTime'])
pinfo

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [10]:
# 4. Total bill amount per department

dept_bill = pinfo.groupby('Department', as_index=False)['BillAmount'].sum()
print(dept_bill)

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

In [11]:
# 5. Removing duplicate patient records

pinfo = pinfo.drop_duplicates(subset='PatientID')
pinfo

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [22]:
# 6. Filling missing BillAmount values with mean amount 

pinfo['BillAmount'] = pd.to_numeric(pinfo['BillAmount'], errors='coerce')
mean_amt = pinfo.loc[pinfo['BillAmount'] != 0, 'BillAmount'].mean()
pinfo['BillAmount'] = pinfo['BillAmount'].fillna( mean_amt)
print(pinfo)

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

C:\Users\revan\AppData\Local\Temp\ipykernel_28684\1806225881.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pinfo['BillAmount'] = pd.to_numeric(pinfo['BillAmount'], errors='coerce')
C:\Users\revan\AppData\Local\Temp\ipykernel_28684\1806225881.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pinfo['BillAmount'] = pinfo['BillAmount'].fillna( mean_amt)

In [23]:
# 7. Merge billing dataset with patient dataset

merged = pd.merge(pinfo, bill, on = 'PatientID', how = 'inner')
merged.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [24]:
# 8. Concatinating new data frame with new patients

new_patients = pd.DataFrame({
    'PatientID': [106, 107, 108, 109, 110],
    'Name' : ['Gracy', 'Shrutee', 'Brian', 'Alex', 'Stacy'],
    'Department': ['Cardiology', 'dermatology', 'Neurology', 'orthopedics', 'dermatology'],
    'Doctor': ['Dr. Smith', 'Dr. Rose', 'Dr. John', 'Dr. Lee', 'Dr. Rose'],
    'BillAmount': [6000.00, 4500.00, 5500.00, 5300.00, 7300.00]
})

new_patients

   PatientID     Name   Department     Doctor  BillAmount
0        106    Gracy   Cardiology  Dr. Smith      6000.0
1        107  Shrutee  dermatology   Dr. Rose      4500.0
2        108    Brian    Neurology   Dr. John      5500.0
3        109     Alex  orthopedics    Dr. Lee      5300.0
4        110    Stacy  dermatology   Dr. Rose      7300.0

In [25]:
concat_1 = pd.concat([pinfo, new_patients], axis=0, ignore_index=True)
concat_1

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106    Gracy   Cardiology  Dr. Smith  6000.000000
6        107  Shrutee  dermatology   Dr. Rose  4500.000000
7        108    Brian    Neurology   Dr. John  5500.000000
8        109     Alex  orthopedics    Dr. Lee  5300.000000
9        110    Stacy  dermatology   Dr. Rose  7300.000000

In [26]:
bill

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [27]:
pinfo

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [28]:
# 9. Concatinating new billing columns
new_cols = pd.DataFrame({
    'InsuranceCovered': [2000, 1500, 2500, 3000, 1000, 2000, 1500, 2500, 3000, 1100],  # example values
    'FinalAmount': concat_1['BillAmount'] * 0.9          # 10% discount
})

new_cols

   InsuranceCovered  FinalAmount
0              2000       4500.0
1              1500       5610.0
2              2500       6750.0
3              3000       5580.0
4              1000       5610.0
5              2000       5400.0
6              1500       4050.0
7              2500       4950.0
8              3000       4770.0
9              1100       6570.0

In [29]:
final_data = pd.concat([concat_1, new_cols], axis=1)
final_data

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,4500.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500,5610.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,6750.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,5580.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,5610.0
5,106,Gracy,Cardiology,Dr. Smith,6000.000000,2000,5400.0
6,107,Shrutee,dermatology,Dr. Rose,4500.000000,1500,4050.0
7,108,Brian,Neurology,Dr. John,5500.000000,2500,4950.0
8,109,Alex,orthopedics,Dr. Lee,5300.000000,3000,4770.0
9,110,Stacy,dermatology,Dr. Rose,7300.000000,1100,6570.0

In [30]:
final_data.isnull().sum()

PatientID           0
Name                0
Department          0
Doctor              0
BillAmount          0
InsuranceCovered    0
FinalAmount         0
dtype: int64

In [32]:
final_data.duplicated().sum()

np.int64(0)

In [33]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         10 non-null     int64
 1   Name              10 non-null     object
 2   Department        10 non-null     object
 3   Doctor            10 non-null     object
 4   BillAmount        10 non-null     float64
 5   InsuranceCovered  10 non-null     int64
 6   FinalAmount       10 non-null     float64
dtypes: float64(2), int64(2), object(3)
memory usage: 692.0+ bytes

In [34]:
final_data.describe()

       PatientID   BillAmount  InsuranceCovered  FinalAmount
count   10.00000    10.000000         10.000000    10.000000
mean   105.50000  5976.666667       2010.000000  5379.000000
std      3.02765   947.126910        730.981076   852.414219
min    101.00000  4500.000000       1000.000000  4050.000000
25%    103.25000  5350.000000       1500.000000  4815.000000
50%    105.50000  6100.000000       2000.000000  5490.000000
75%    107.75000  6233.333333       2500.000000  5610.000000
max    110.00000  7500.000000       3000.000000  6750.000000